import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import Header from '@/components/Header'
import { urbanist } from './fonts'
import Menu from '@/components/Menu'
import Breadcrumb from '@/components/Breadcrumb'
import Button from '@/components/Button'
import { getServerSession } from 'next-auth'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const userSession = await getServerSession()
  console.log('userSession', userSession)
  return (
    <html lang='ja'>
      <body className='mb-36'>
        <Header />
        {children}
        <Menu />
      </body>
    </html>
  )
}
