import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/globals.css'
import Header from './components/Header'
import { urbanist } from './fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <Header />
        {children}</body>
    </html>
  )
}
