import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/globals.css'
import Header from './components/Header'
import { urbanist } from './fonts'
import Menu from './components/Menu'
import Breadcrumb from './components/Breadcrumb'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <Header />
        {children}
        <Menu />
        </body>
    </html>
  )
}
